// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkpErXFDAPP6wlXmWglWK0JZKoRfTmTsE',
    appId: '1:422830734613:web:738a40381aa6310e06bd1c',
    messagingSenderId: '422830734613',
    projectId: 'optim-air-75ca0',
    authDomain: 'optim-air-75ca0.firebaseapp.com',
    storageBucket: 'optim-air-75ca0.firebasestorage.app',
    measurementId: 'G-FQPJ62G53J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs3x3C3qk0Z5zUm2oDjpgGLZGUNEPQSJc',
    appId: '1:422830734613:android:bc3f7ea90a54ef8106bd1c',
    messagingSenderId: '422830734613',
    projectId: 'optim-air-75ca0',
    storageBucket: 'optim-air-75ca0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4oRZkMKLtTeyBSEM4EGhbn8TiNUqtrmw',
    appId: '1:422830734613:ios:2c198cdef40be66206bd1c',
    messagingSenderId: '422830734613',
    projectId: 'optim-air-75ca0',
    storageBucket: 'optim-air-75ca0.firebasestorage.app',
    iosBundleId: 'com.example.optimair',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4oRZkMKLtTeyBSEM4EGhbn8TiNUqtrmw',
    appId: '1:422830734613:ios:2c198cdef40be66206bd1c',
    messagingSenderId: '422830734613',
    projectId: 'optim-air-75ca0',
    storageBucket: 'optim-air-75ca0.firebasestorage.app',
    iosBundleId: 'com.example.optimair',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkpErXFDAPP6wlXmWglWK0JZKoRfTmTsE',
    appId: '1:422830734613:web:e76ef0419b44962706bd1c',
    messagingSenderId: '422830734613',
    projectId: 'optim-air-75ca0',
    authDomain: 'optim-air-75ca0.firebaseapp.com',
    storageBucket: 'optim-air-75ca0.firebasestorage.app',
    measurementId: 'G-L5MDRM6KB0',
  );
}
