name: Weather Data Collector

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  collect-weather-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Cache Python Dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create Required Directories
      run: |
        mkdir -p data logs
        echo "📁 Dossiers créés"
    
    - name: Run Weather Data Collection
      env:
        GCP_AIR_QUALITY_API_KEY: ${{ secrets.GCP_AIR_QUALITY_API_KEY }}
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        FIREBASE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
        DEFAULT_LATITUDE: 48.8566
        DEFAULT_LONGITUDE: 2.3522
        LOG_LEVEL: INFO
      run: |
        echo "🚀 Démarrage de la collecte de données météo"
        echo "📍 Localisation: Paris (48.8566, 2.3522)"
        echo "⏰ Timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
        
        python main.py
        
        echo "✅ Collecte terminée"
    
    - name: Show Results
      if: always()
      run: |
        echo "📊 Vérification des fichiers générés:"
        ls -la data/ || echo "Pas de dossier data"
        ls -la logs/ || echo "Pas de dossier logs"
        
        if [ -f "data/latest_data.json" ]; then
          echo "✅ Fichier de données trouvé"
          head -n 10 data/latest_data.json
        else
          echo "❌ Pas de fichier de données"
        fi
    
    - name: Upload Data Files
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: weather-data-${{ github.run_number }}
        path: data/
        retention-days: 7
        if-no-files-found: warn
